---
title: "NEON_data_grab"
authors: Kade Stewart, 
output: html_document
date: "2026-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Library:
```{r library}
library(tidyverse)
library(here)
library(neonUtilities)
```

## EXAMPLE SCRIPT!!!
```{r pressure, echo=FALSE}
# Mosquitoes sampled from CO2 traps
#mosquito <- "DP1.10043.001"

# Precipitation - weighing gauge
#precipitation <- "DP1.00044.001"

# Select two focal sites for now
#my_sites <- c("BART", "WOOD")

# Start date (as YYYY-MM)
#start_date <- "2020-01"

# End date (as YYYY-MM)
#end_date <- "2022-12"

#list2env((loadByProduct(dpID = mosquito, 
 #                       site = my_sites, 
  #                      include.provisional = FALSE,
   #                     startdate = start_date,
    #                    enddate = end_date)),
     #    .GlobalEnv)

# Variable names and units: mosquitoes
#variables_10043 %>% 
#  write_csv(here("data", "raw", "variables_10043.csv"))

#rm(list = ls())
```

Hey this is a test on 2/17/2026!

First attempt at pulling NEON Data: 2/17
```{r}
#Pull data
discharge <- "DP4.00130.001"

#Select sites and dates *DATES SHOULD BE REEVALUATED
my_sites <- c("BIGC", "TECR")
start_date <- "2018-11"
end_date <- "2022-12"

#Pull
list2env((loadByProduct(dpID = discharge, 
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```

```{r}
#Save raw data
variables_00130 %>% 
  write_csv(here("data", "raw", "variables_00130.csv"))

csd_continuousDischarge %>% 
  write_csv(here("data", "raw", "discharge_raw.csv"))

```


```{r}
#Pull data from	"Fish electrofishing, gill netting, and fyke netting counts"
fish <- "DP1.20107.001"

#Select sites and dates 
my_sites <- c("BIGC", "TECR")
start_date <- "2012-01"
end_date <- "2022-12"

#Pull
list2env((loadByProduct(dpID = fish, 
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```

```{r}
<<<<<<< HEAD
#Pull data from "Aquatic plants"
plants <- "DP1.20072.001"

#Select sites and dates *DATES SHOULD BE REEVALUATED
=======
#Benthic microbe community composition, DP1.20086.001

benthic <- "DP1.20086.001"

#Select sites and dates 
>>>>>>> 380eacbb67e133bc31e9c0d89ce02c328868e615
my_sites <- c("BIGC", "TECR")
start_date <- "2012-01"
end_date <- "2022-12"

#Pull
<<<<<<< HEAD
list2env((loadByProduct(dpID = plants, 
=======
list2env((loadByProduct(dpID = benthic, 
>>>>>>> 380eacbb67e133bc31e9c0d89ce02c328868e615
                        site = my_sites, 
                        include.provisional = FALSE,
                        startdate = start_date,
                        enddate = end_date)),
         .GlobalEnv)
```
<<<<<<< HEAD
=======

>>>>>>> 380eacbb67e133bc31e9c0d89ce02c328868e615
